마크다운 이미지 가져오기 구현 (#26)
NAVER-CAMPUS-HACKDAY/contents-proxy-blog pull request #30
Opened 2018-11-29 17:10 UTC by hyukjin-lee

### 구현 방식
* 상대경로와 절대경로로 구분지을 수 있다. 절대경로는 딱히 손대지 않아도 이미지를 가져온다.
* 상대경로는 repoUrl을 앞에 붙여주고 blob/master과 해당 image의 경로를 넣어주어야한다.
* regex를 사용하여 이미지 상대경로를 추출해내서 url을 재조합한다.
### 어려웠던 사항
* 경로를 제대로 입력했지만 이미지가 뜨지 않는 현상이 발생했다.
* 원인은 github.com/~~~~/~~.png 이런식으로 접근하면 github 페이지가 나오는 것이지 해당 이미지 데이터에 접근하는 것이 아니다.
* 해당 이미지 데이터에 접근하기 위해 download 버튼을 누르니까 github.com이 아니라raw.githubusercontent.com 이고 blob이 없어서 바꾸어주었다.

2018-11-29 17:18 UTC, so3500 approved these changes

2018-11-29 22:49 UTC, benelog requested changes
어려운 기능이라 생각했는데, 잘 구현하셨네요. 👍 

Pattern.compile을 최적화하는 것만 한번 시도해보시면 좋을거 같습니다.

2018-11-29 23:59 UTC, so3500 approved these changes

2018-11-30 02:00 UTC, benelog approved these changes

2018-11-30 02:18 UTC, merged